### PR TITLE
chore: bump dependencies

### PR DESCRIPTION
**Pull request by fcs-ts**

### CODE REVIEW

**Comment by jbergstroem** [comment]
Perhaps set up renovatebot? You can copy a template from other repos (topsort.js,docs,proxy,puma,..) and edit as you see fit.

**Review by anonvt — APPROVED** [review]

**Comment by jbergstroem** [comment]
On raising SDK: does this affect what version we support?

**Comment by pitbuster** [comment]
> On raising SDK: does this affect what version we support?

It shouldn't, `minSdk` would do that as far as I know.

**Comment by fcs-ts** [comment]
> On raising SDK: does this affect what version we support?

It shouldn't, that would be the role of `minSdk`, which isn't touched, as far as I know

**Pull request merged**
